### ISSUE TITLE
7.0 update?

### ISSUE THREAD

**Issue by zenrar** [paissaheavyindustries/Tallafell#1]
is there a Update scheduled anytime soon for 7.0?

**Comment by spooee** [comment]
Hello,
I forked the repo and updated it for Dawntrail, it's available here: https://github.com/spooee/Tallafell
You'll have to add it yourself as a dev plugin, as I did not add it to my own plugin repo.
Let me know if there are any issues.

**Comment by paissaheavyindustries** [comment]
updated for api 11 / 7.1
